version: '3.8'

services:
  typesense:
    image: typesense/typesense:29.0.rc4-amd64
    container_name: typesense
    ports:
      - "8108:8108"
    volumes:
      - typesense_data:/data
    environment:
      - TYPESENSE_API_KEY=xyz123
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_ENABLE_CORS=true

  typesense-dashboard:
    image: fulldigits/typesense-dashboard:latest
    container_name: typesense-dashboard
    ports:
      - "5000:80"
    environment:
      - VITE_TYPESENSE_HOST=http://typesense:8108/
      - VITE_TYPESENSE_API_KEY=xyz123
    depends_on:
      - typesense

volumes:
  typesense_data: